# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GsolveGUIv3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Gsolve(object):
    def setupUi(self, Gsolve):
        Gsolve.setObjectName(_fromUtf8("Gsolve"))
        Gsolve.resize(1251, 834)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Gsolve.sizePolicy().hasHeightForWidth())
        Gsolve.setSizePolicy(sizePolicy)
        Gsolve.setMinimumSize(QtCore.QSize(0, 0))
        Gsolve.setTabShape(QtGui.QTabWidget.Rounded)
        Gsolve.setDockNestingEnabled(False)
        Gsolve.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(Gsolve)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.toolBox = QtGui.QToolBox(self.centralwidget)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 833, 714))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.page_5)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.AddNewSurveyMeasurement = QtGui.QPushButton(self.tab)
        self.AddNewSurveyMeasurement.setObjectName(_fromUtf8("AddNewSurveyMeasurement"))
        self.gridLayout_6.addWidget(self.AddNewSurveyMeasurement, 0, 3, 1, 1)
        self.RemoveSurveyMeasurement = QtGui.QPushButton(self.tab)
        self.RemoveSurveyMeasurement.setObjectName(_fromUtf8("RemoveSurveyMeasurement"))
        self.gridLayout_6.addWidget(self.RemoveSurveyMeasurement, 0, 4, 1, 1)
        self.SaveSurveyData = QtGui.QPushButton(self.tab)
        self.SaveSurveyData.setObjectName(_fromUtf8("SaveSurveyData"))
        self.gridLayout_6.addWidget(self.SaveSurveyData, 0, 1, 1, 1)
        self.ImportsureveyData = QtGui.QPushButton(self.tab)
        self.ImportsureveyData.setObjectName(_fromUtf8("ImportsureveyData"))
        self.gridLayout_6.addWidget(self.ImportsureveyData, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 1, 2, 1, 1)
        self.SurveyDataTab = QtGui.QTableWidget(self.tab)
        self.SurveyDataTab.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.SurveyDataTab.setDragEnabled(True)
        self.SurveyDataTab.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.SurveyDataTab.setObjectName(_fromUtf8("SurveyDataTab"))
        self.SurveyDataTab.setColumnCount(11)
        self.SurveyDataTab.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyDataTab.setHorizontalHeaderItem(10, item)
        self.gridLayout_6.addWidget(self.SurveyDataTab, 2, 0, 1, 6)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.frame_6 = QtGui.QFrame(self.tab_3)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.frame_4 = QtGui.QFrame(self.frame_6)
        self.frame_4.setMinimumSize(QtCore.QSize(291, 611))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label = QtGui.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 10, 46, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.CalTabSelect = QtGui.QComboBox(self.frame_4)
        self.CalTabSelect.setGeometry(QtCore.QRect(10, 50, 261, 21))
        self.CalTabSelect.setObjectName(_fromUtf8("CalTabSelect"))
        self.label_2 = QtGui.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 131, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.UseLoops = QtGui.QCheckBox(self.frame_4)
        self.UseLoops.setGeometry(QtCore.QRect(20, 340, 82, 17))
        self.UseLoops.setObjectName(_fromUtf8("UseLoops"))
        self.label_3 = QtGui.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 141, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.AddNewAbsTie = QtGui.QPushButton(self.frame_4)
        self.AddNewAbsTie.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.AddNewAbsTie.setObjectName(_fromUtf8("AddNewAbsTie"))
        self.RemoveAbsTie = QtGui.QPushButton(self.frame_4)
        self.RemoveAbsTie.setGeometry(QtCore.QRect(160, 110, 75, 23))
        self.RemoveAbsTie.setObjectName(_fromUtf8("RemoveAbsTie"))
        self.SurveyTies = QtGui.QTableWidget(self.frame_4)
        self.SurveyTies.setGeometry(QtCore.QRect(10, 140, 221, 192))
        self.SurveyTies.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.SurveyTies.setObjectName(_fromUtf8("SurveyTies"))
        self.SurveyTies.setColumnCount(2)
        self.SurveyTies.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.SurveyTies.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.SurveyTies.setHorizontalHeaderItem(1, item)
        self.MethodSelect = QtGui.QComboBox(self.frame_4)
        self.MethodSelect.setGeometry(QtCore.QRect(10, 510, 261, 21))
        self.MethodSelect.setObjectName(_fromUtf8("MethodSelect"))
        self.MethodSelect.addItem(_fromUtf8(""))
        self.MethodSelect.addItem(_fromUtf8(""))
        self.MethodSelect.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 490, 131, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.SolveAll = QtGui.QPushButton(self.frame_4)
        self.SolveAll.setGeometry(QtCore.QRect(10, 540, 261, 51))
        self.SolveAll.setObjectName(_fromUtf8("SolveAll"))
        self.CalculateBeta = QtGui.QCheckBox(self.frame_4)
        self.CalculateBeta.setGeometry(QtCore.QRect(20, 460, 151, 17))
        self.CalculateBeta.setObjectName(_fromUtf8("CalculateBeta"))
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(20, 410, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.BetaIne = QtGui.QLineEdit(self.frame_4)
        self.BetaIne.setGeometry(QtCore.QRect(20, 430, 113, 20))
        self.BetaIne.setObjectName(_fromUtf8("BetaIne"))
        self.ConfInt = QtGui.QLineEdit(self.frame_4)
        self.ConfInt.setGeometry(QtCore.QRect(20, 380, 113, 20))
        self.ConfInt.setObjectName(_fromUtf8("ConfInt"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(20, 360, 151, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_11.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_10 = QtGui.QFrame(self.frame_6)
        self.frame_10.setMinimumSize(QtCore.QSize(471, 631))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_8 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_15.addWidget(self.label_8, 0, 0, 1, 1)
        self.MainResultsTabview = QtGui.QTableWidget(self.frame_10)
        self.MainResultsTabview.setMinimumSize(QtCore.QSize(421, 0))
        self.MainResultsTabview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.MainResultsTabview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.MainResultsTabview.setObjectName(_fromUtf8("MainResultsTabview"))
        self.MainResultsTabview.setColumnCount(4)
        self.MainResultsTabview.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.MainResultsTabview.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MainResultsTabview.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.MainResultsTabview.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.MainResultsTabview.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.MainResultsTabview.setHorizontalHeaderItem(3, item)
        self.gridLayout_15.addWidget(self.MainResultsTabview, 1, 0, 1, 2)
        self.ExportResults = QtGui.QPushButton(self.frame_10)
        self.ExportResults.setObjectName(_fromUtf8("ExportResults"))
        self.gridLayout_15.addWidget(self.ExportResults, 2, 1, 1, 1)
        self.gridLayout_11.addWidget(self.frame_10, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.frame_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.frame_9 = QtGui.QFrame(self.tab_4)
        self.frame_9.setMinimumSize(QtCore.QSize(231, 61))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label_6 = QtGui.QLabel(self.frame_9)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.LoopCDFSel = QtGui.QComboBox(self.frame_9)
        self.LoopCDFSel.setGeometry(QtCore.QRect(0, 20, 81, 21))
        self.LoopCDFSel.setObjectName(_fromUtf8("LoopCDFSel"))
        self.LoopCDFSel.addItem(_fromUtf8(""))
        self.CDFplot = QtGui.QPushButton(self.frame_9)
        self.CDFplot.setGeometry(QtCore.QRect(90, 20, 121, 21))
        self.CDFplot.setObjectName(_fromUtf8("CDFplot"))
        self.LoopSel_2 = QtGui.QComboBox(self.frame_9)
        self.LoopSel_2.setGeometry(QtCore.QRect(0, 70, 81, 21))
        self.LoopSel_2.setObjectName(_fromUtf8("LoopSel_2"))
        self.LoopSel_2.addItem(_fromUtf8(""))
        self.driftplot_2 = QtGui.QPushButton(self.frame_9)
        self.driftplot_2.setGeometry(QtCore.QRect(90, 70, 121, 21))
        self.driftplot_2.setObjectName(_fromUtf8("driftplot_2"))
        self.gridLayout_10.addWidget(self.frame_9, 1, 2, 1, 1)
        self.frame_8 = QtGui.QFrame(self.tab_4)
        self.frame_8.setMinimumSize(QtCore.QSize(141, 41))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.BetaOut = QtGui.QLineEdit(self.frame_8)
        self.BetaOut.setGeometry(QtCore.QRect(10, 20, 113, 20))
        self.BetaOut.setReadOnly(True)
        self.BetaOut.setObjectName(_fromUtf8("BetaOut"))
        self.label_7 = QtGui.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 121, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.frame_8, 1, 1, 1, 1)
        self.DetailedResultsTabview = QtGui.QTableWidget(self.tab_4)
        self.DetailedResultsTabview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.DetailedResultsTabview.setObjectName(_fromUtf8("DetailedResultsTabview"))
        self.DetailedResultsTabview.setColumnCount(14)
        self.DetailedResultsTabview.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.DetailedResultsTabview.setHorizontalHeaderItem(13, item)
        self.gridLayout_10.addWidget(self.DetailedResultsTabview, 0, 0, 1, 4)
        self.DriftTabview = QtGui.QTableWidget(self.tab_4)
        self.DriftTabview.setMinimumSize(QtCore.QSize(231, 192))
        self.DriftTabview.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.DriftTabview.setObjectName(_fromUtf8("DriftTabview"))
        self.DriftTabview.setColumnCount(2)
        self.DriftTabview.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.DriftTabview.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DriftTabview.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.DriftTabview.setHorizontalHeaderItem(1, item)
        self.gridLayout_10.addWidget(self.DriftTabview, 1, 0, 2, 1)
        self.ExportDetailedResults = QtGui.QPushButton(self.tab_4)
        self.ExportDetailedResults.setObjectName(_fromUtf8("ExportDetailedResults"))
        self.gridLayout_10.addWidget(self.ExportDetailedResults, 2, 3, 1, 1)
        self.DetailedResultsTabview.raise_()
        self.DriftTabview.raise_()
        self.ExportDetailedResults.raise_()
        self.frame_8.raise_()
        self.frame_9.raise_()
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout = QtGui.QGridLayout(self.tab_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.GravityReductionsTab = QtGui.QTableWidget(self.tab_5)
        self.GravityReductionsTab.setMinimumSize(QtCore.QSize(781, 0))
        self.GravityReductionsTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.GravityReductionsTab.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GravityReductionsTab.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.GravityReductionsTab.setObjectName(_fromUtf8("GravityReductionsTab"))
        self.GravityReductionsTab.setColumnCount(8)
        self.GravityReductionsTab.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.GravityReductionsTab.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.GravityReductionsTab, 0, 0, 1, 1)
        self.frame_13 = QtGui.QFrame(self.tab_5)
        self.frame_13.setMinimumSize(QtCore.QSize(791, 221))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.ExportGravityreductions = QtGui.QPushButton(self.frame_13)
        self.ExportGravityreductions.setGeometry(QtCore.QRect(660, 20, 121, 31))
        self.ExportGravityreductions.setObjectName(_fromUtf8("ExportGravityreductions"))
        self.Ellipsoidselect = QtGui.QComboBox(self.frame_13)
        self.Ellipsoidselect.setGeometry(QtCore.QRect(10, 30, 221, 21))
        self.Ellipsoidselect.setObjectName(_fromUtf8("Ellipsoidselect"))
        self.Ellipsoidselect.addItem(_fromUtf8(""))
        self.Ellipsoidselect.addItem(_fromUtf8(""))
        self.label_10 = QtGui.QLabel(self.frame_13)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.UpdateEll = QtGui.QPushButton(self.frame_13)
        self.UpdateEll.setGeometry(QtCore.QRect(240, 30, 75, 23))
        self.UpdateEll.setObjectName(_fromUtf8("UpdateEll"))
        self.gridLayout.addWidget(self.frame_13, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.toolBox.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 807, 722))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget_7 = QtGui.QTabWidget(self.page_6)
        self.tabWidget_7.setObjectName(_fromUtf8("tabWidget_7"))
        self.Importdata = QtGui.QWidget()
        self.Importdata.setObjectName(_fromUtf8("Importdata"))
        self.formLayout_3 = QtGui.QFormLayout(self.Importdata)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.frame_7 = QtGui.QFrame(self.Importdata)
        self.frame_7.setMinimumSize(QtCore.QSize(161, 659))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ImportDEM = QtGui.QPushButton(self.frame_7)
        self.ImportDEM.setObjectName(_fromUtf8("ImportDEM"))
        self.gridLayout_2.addWidget(self.ImportDEM, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.frame_7)
        self.groupBox_2.setMinimumSize(QtCore.QSize(161, 71))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.Resolution = QtGui.QLineEdit(self.groupBox_2)
        self.Resolution.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.Resolution.setObjectName(_fromUtf8("Resolution"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.frame_7)
        self.frame_14 = QtGui.QFrame(self.Importdata)
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_14)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.mplwidget = MatplotlibWidget(self.frame_14)
        self.mplwidget.setAutoFillBackground(True)
        self.mplwidget.setStyleSheet(_fromUtf8(""))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.gridLayout_17.addWidget(self.mplwidget, 1, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(387, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem1, 0, 1, 1, 1)
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_14)
        self.tabWidget_7.addTab(self.Importdata, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab_6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.widget_2 = QtGui.QWidget(self.tab_6)
        self.widget_2.setMinimumSize(QtCore.QSize(759, 659))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.EastingsNorthingsTC = QtGui.QTableWidget(self.widget_2)
        self.EastingsNorthingsTC.setGeometry(QtCore.QRect(10, 40, 741, 601))
        self.EastingsNorthingsTC.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.EastingsNorthingsTC.setObjectName(_fromUtf8("EastingsNorthingsTC"))
        self.EastingsNorthingsTC.setColumnCount(7)
        self.EastingsNorthingsTC.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC.setHorizontalHeaderItem(6, item)
        self.ImportdatapointsTC = QtGui.QPushButton(self.widget_2)
        self.ImportdatapointsTC.setGeometry(QtCore.QRect(10, 10, 131, 23))
        self.ImportdatapointsTC.setObjectName(_fromUtf8("ImportdatapointsTC"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.widget_2)
        self.tabWidget_7.addTab(self.tab_6, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.formLayout = QtGui.QFormLayout(self.tab_7)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.frame_16 = QtGui.QFrame(self.tab_7)
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName(_fromUtf8("frame_16"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frame_16)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        spacerItem2 = QtGui.QSpacerItem(387, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem2, 0, 1, 1, 1)
        self.TCplot2 = MatplotlibWidget(self.frame_16)
        self.TCplot2.setAutoFillBackground(True)
        self.TCplot2.setStyleSheet(_fromUtf8(""))
        self.TCplot2.setObjectName(_fromUtf8("TCplot2"))
        self.gridLayout_18.addWidget(self.TCplot2, 1, 0, 1, 3)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame_16)
        self.frame_15 = QtGui.QFrame(self.tab_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMinimumSize(QtCore.QSize(166, 651))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.groupBox = QtGui.QGroupBox(self.frame_15)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 151, 641))
        self.groupBox.setMinimumSize(QtCore.QSize(151, 392))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.outterradTC = QtGui.QLineEdit(self.groupBox)
        self.outterradTC.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.outterradTC.setObjectName(_fromUtf8("outterradTC"))
        self.innerradTC = QtGui.QLineEdit(self.groupBox)
        self.innerradTC.setGeometry(QtCore.QRect(10, 50, 113, 20))
        self.innerradTC.setObjectName(_fromUtf8("innerradTC"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.density = QtGui.QLineEdit(self.groupBox)
        self.density.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.density.setObjectName(_fromUtf8("density"))
        self.CalcTC = QtGui.QPushButton(self.groupBox)
        self.CalcTC.setGeometry(QtCore.QRect(0, 180, 151, 51))
        self.CalcTC.setObjectName(_fromUtf8("CalcTC"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.frame_15)
        self.tabWidget_7.addTab(self.tab_7, _fromUtf8(""))
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName(_fromUtf8("tab_8"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab_8)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_3 = QtGui.QWidget(self.tab_8)
        self.widget_3.setMinimumSize(QtCore.QSize(759, 659))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.EastingsNorthingsTC_results = QtGui.QTableWidget(self.widget_3)
        self.EastingsNorthingsTC_results.setGeometry(QtCore.QRect(0, 20, 751, 461))
        self.EastingsNorthingsTC_results.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.EastingsNorthingsTC_results.setObjectName(_fromUtf8("EastingsNorthingsTC_results"))
        self.EastingsNorthingsTC_results.setColumnCount(8)
        self.EastingsNorthingsTC_results.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.EastingsNorthingsTC_results.setHorizontalHeaderItem(7, item)
        self.ExportTCresults = QtGui.QPushButton(self.widget_3)
        self.ExportTCresults.setGeometry(QtCore.QRect(610, 630, 131, 23))
        self.ExportTCresults.setObjectName(_fromUtf8("ExportTCresults"))
        self.TCparameter_results = QtGui.QTableWidget(self.widget_3)
        self.TCparameter_results.setGeometry(QtCore.QRect(0, 500, 421, 61))
        self.TCparameter_results.setMinimumSize(QtCore.QSize(421, 61))
        self.TCparameter_results.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.TCparameter_results.setObjectName(_fromUtf8("TCparameter_results"))
        self.TCparameter_results.setColumnCount(4)
        self.TCparameter_results.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.TCparameter_results.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TCparameter_results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TCparameter_results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TCparameter_results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.TCparameter_results.setHorizontalHeaderItem(3, item)
        self.horizontalLayout.addWidget(self.widget_3)
        self.tabWidget_7.addTab(self.tab_8, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget_7)
        self.toolBox.addItem(self.page_6, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.toolBox)
        Gsolve.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(Gsolve)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        Gsolve.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(Gsolve)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Gsolve.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(Gsolve)
        self.dockWidget.setMinimumSize(QtCore.QSize(428, 793))
        self.dockWidget.setBaseSize(QtCore.QSize(428, 763))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ImportNewAbdG = QtGui.QTabWidget(self.dockWidgetContents_2)
        self.ImportNewAbdG.setObjectName(_fromUtf8("ImportNewAbdG"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.CalibrationTabSelectview = QtGui.QComboBox(self.frame_2)
        self.CalibrationTabSelectview.setMaximumSize(QtCore.QSize(16777215, 23))
        self.CalibrationTabSelectview.setObjectName(_fromUtf8("CalibrationTabSelectview"))
        self.verticalLayout_3.addWidget(self.CalibrationTabSelectview)
        self.CalibrationTabView = QtGui.QTableWidget(self.frame_2)
        self.CalibrationTabView.setMouseTracking(False)
        self.CalibrationTabView.setAutoFillBackground(False)
        self.CalibrationTabView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.CalibrationTabView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.CalibrationTabView.setObjectName(_fromUtf8("CalibrationTabView"))
        self.CalibrationTabView.setColumnCount(3)
        self.CalibrationTabView.setRowCount(10)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.CalibrationTabView.setHorizontalHeaderItem(2, item)
        self.CalibrationTabView.horizontalHeader().setDefaultSectionSize(90)
        self.verticalLayout_3.addWidget(self.CalibrationTabView)
        self.gridLayout_8.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(71, 659))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.ImportNewCalTab = QtGui.QPushButton(self.frame_3)
        self.ImportNewCalTab.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.ImportNewCalTab.setObjectName(_fromUtf8("ImportNewCalTab"))
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 580, 71, 80))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_8.addWidget(self.frame_3, 0, 0, 1, 1)
        self.RemoveCalTab = QtGui.QPushButton(self.frame_2)
        self.RemoveCalTab.setObjectName(_fromUtf8("RemoveCalTab"))
        self.gridLayout_8.addWidget(self.RemoveCalTab, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.ImportNewAbdG.addTab(self.tab_2, _fromUtf8(""))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widget)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.frame = QtGui.QFrame(self.widget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.AbsGTabview = QtGui.QTableWidget(self.frame)
        self.AbsGTabview.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.AbsGTabview.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.AbsGTabview.setObjectName(_fromUtf8("AbsGTabview"))
        self.AbsGTabview.setColumnCount(4)
        self.AbsGTabview.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.AbsGTabview.setHorizontalHeaderItem(3, item)
        self.gridLayout_14.addWidget(self.AbsGTabview, 0, 1, 2, 2)
        self.frame_12 = QtGui.QFrame(self.frame)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 51))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_12)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.RemoveAbsG = QtGui.QPushButton(self.frame_12)
        self.RemoveAbsG.setObjectName(_fromUtf8("RemoveAbsG"))
        self.gridLayout_12.addWidget(self.RemoveAbsG, 0, 1, 1, 1)
        self.SaveNewAbsG = QtGui.QPushButton(self.frame_12)
        self.SaveNewAbsG.setObjectName(_fromUtf8("SaveNewAbsG"))
        self.gridLayout_12.addWidget(self.SaveNewAbsG, 0, 2, 1, 1)
        self.AddNewAbsG = QtGui.QPushButton(self.frame_12)
        self.AddNewAbsG.setObjectName(_fromUtf8("AddNewAbsG"))
        self.gridLayout_12.addWidget(self.AddNewAbsG, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_12, 2, 1, 1, 1)
        self.frame_11 = QtGui.QFrame(self.frame)
        self.frame_11.setMinimumSize(QtCore.QSize(81, 0))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName(_fromUtf8("frame_11"))
        self.ImportNewAbsG = QtGui.QPushButton(self.frame_11)
        self.ImportNewAbsG.setGeometry(QtCore.QRect(0, 10, 71, 31))
        self.ImportNewAbsG.setObjectName(_fromUtf8("ImportNewAbsG"))
        self.gridLayout_14.addWidget(self.frame_11, 0, 0, 2, 1)
        self.gridLayout_13.addWidget(self.frame, 0, 0, 1, 1)
        self.ImportNewAbdG.addTab(self.widget, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.ImportNewAbdG, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        Gsolve.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionNew = QtGui.QAction(Gsolve)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(Gsolve)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(Gsolve)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(Gsolve)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionGsolve_Help = QtGui.QAction(Gsolve)
        self.actionGsolve_Help.setObjectName(_fromUtf8("actionGsolve_Help"))
        self.actionAbout = QtGui.QAction(Gsolve)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menu_File.addAction(self.actionNew)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionGsolve_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Gsolve)
        self.toolBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_7.setCurrentIndex(0)
        self.ImportNewAbdG.setCurrentIndex(1)
        QtCore.QObject.connect(self.CalculateBeta, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.BetaIne.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Gsolve)

    def retranslateUi(self, Gsolve):
        Gsolve.setWindowTitle(_translate("Gsolve", "Gsolve", None))
        self.AddNewSurveyMeasurement.setText(_translate("Gsolve", "Add New", None))
        self.RemoveSurveyMeasurement.setText(_translate("Gsolve", "Remove", None))
        self.SaveSurveyData.setText(_translate("Gsolve", "Save Survey Data", None))
        self.ImportsureveyData.setText(_translate("Gsolve", "Import", None))
        item = self.SurveyDataTab.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.SurveyDataTab.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.SurveyDataTab.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Latitude", None))
        item = self.SurveyDataTab.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Longitude", None))
        item = self.SurveyDataTab.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Elevation", None))
        item = self.SurveyDataTab.horizontalHeaderItem(4)
        item.setText(_translate("Gsolve", "Dial", None))
        item = self.SurveyDataTab.horizontalHeaderItem(5)
        item.setText(_translate("Gsolve", "Day", None))
        item = self.SurveyDataTab.horizontalHeaderItem(6)
        item.setText(_translate("Gsolve", "Month", None))
        item = self.SurveyDataTab.horizontalHeaderItem(7)
        item.setText(_translate("Gsolve", "Year", None))
        item = self.SurveyDataTab.horizontalHeaderItem(8)
        item.setText(_translate("Gsolve", "Hour", None))
        item = self.SurveyDataTab.horizontalHeaderItem(9)
        item.setText(_translate("Gsolve", "Minute", None))
        item = self.SurveyDataTab.horizontalHeaderItem(10)
        item.setText(_translate("Gsolve", "Loop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Gsolve", "Survey Data", None))
        self.label.setText(_translate("Gsolve", "Settings", None))
        self.label_2.setText(_translate("Gsolve", "Select Calibration Table:", None))
        self.UseLoops.setText(_translate("Gsolve", "Use Loops", None))
        self.label_3.setText(_translate("Gsolve", "Select Asolute Gravity Ties:", None))
        self.AddNewAbsTie.setText(_translate("Gsolve", "Add New", None))
        self.RemoveAbsTie.setText(_translate("Gsolve", "Remove", None))
        item = self.SurveyTies.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Names", None))
        item = self.SurveyTies.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Absolute Gravity", None))
        self.MethodSelect.setItemText(0, _translate("Gsolve", "Method 1: Normal Least Squares", None))
        self.MethodSelect.setItemText(1, _translate("Gsolve", "Method 2: Decoupled Least Squares", None))
        self.MethodSelect.setItemText(2, _translate("Gsolve", "Method 3: Constrained Least Squares", None))
        self.label_4.setText(_translate("Gsolve", "Select Solution Method:", None))
        self.SolveAll.setText(_translate("Gsolve", "Solve", None))
        self.CalculateBeta.setText(_translate("Gsolve", "Calculate Calibration Factor", None))
        self.label_5.setText(_translate("Gsolve", "Beta Calibration Factor:", None))
        self.BetaIne.setText(_translate("Gsolve", "0", None))
        self.ConfInt.setText(_translate("Gsolve", "100", None))
        self.label_9.setText(_translate("Gsolve", "Residual Confidence Interval:", None))
        self.label_8.setText(_translate("Gsolve", "Results:", None))
        item = self.MainResultsTabview.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.MainResultsTabview.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.MainResultsTabview.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Absolute Gravity", None))
        item = self.MainResultsTabview.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Standard Error", None))
        item = self.MainResultsTabview.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Number Obs.", None))
        self.ExportResults.setText(_translate("Gsolve", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Gsolve", "Solve", None))
        self.label_6.setText(_translate("Gsolve", "Loop:", None))
        self.LoopCDFSel.setItemText(0, _translate("Gsolve", "All", None))
        self.CDFplot.setText(_translate("Gsolve", "CDF plot of residuals", None))
        self.LoopSel_2.setItemText(0, _translate("Gsolve", "All", None))
        self.driftplot_2.setText(_translate("Gsolve", "Plot drift and residuals ", None))
        self.label_7.setText(_translate("Gsolve", "Beta Calibration Factor:", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Latitude", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Longitude", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Elevation", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(4)
        item.setText(_translate("Gsolve", "Dial", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(5)
        item.setText(_translate("Gsolve", "Calibrate Dial", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(6)
        item.setText(_translate("Gsolve", "Day", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(7)
        item.setText(_translate("Gsolve", "Month", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(8)
        item.setText(_translate("Gsolve", "Year", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(9)
        item.setText(_translate("Gsolve", "Hour", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(10)
        item.setText(_translate("Gsolve", "Minute", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(11)
        item.setText(_translate("Gsolve", "Tidal Effect", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(12)
        item.setText(_translate("Gsolve", "Loop", None))
        item = self.DetailedResultsTabview.horizontalHeaderItem(13)
        item.setText(_translate("Gsolve", "Residual", None))
        item = self.DriftTabview.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.DriftTabview.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Loop", None))
        item = self.DriftTabview.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Drift mGal/hour", None))
        self.ExportDetailedResults.setText(_translate("Gsolve", "Export", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Gsolve", "Detailed Results and Plotting", None))
        item = self.GravityReductionsTab.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Absolute Gravity", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Latitude", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Longitude", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(4)
        item.setText(_translate("Gsolve", "Elevation ", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(5)
        item.setText(_translate("Gsolve", "Ellipsoidal Gravity", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(6)
        item.setText(_translate("Gsolve", "Free Air Effect", None))
        item = self.GravityReductionsTab.horizontalHeaderItem(7)
        item.setText(_translate("Gsolve", "Free Air Anomaly", None))
        self.ExportGravityreductions.setText(_translate("Gsolve", "Export", None))
        self.Ellipsoidselect.setItemText(0, _translate("Gsolve", "GRS80", None))
        self.Ellipsoidselect.setItemText(1, _translate("Gsolve", "GRS67", None))
        self.label_10.setText(_translate("Gsolve", "Select an Ellipsoid:", None))
        self.UpdateEll.setText(_translate("Gsolve", "Update", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Gsolve", "Gravity Reductions", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Gsolve", "Relative Gravity Processing", None))
        self.ImportDEM.setText(_translate("Gsolve", "Import DEM", None))
        self.groupBox_2.setTitle(_translate("Gsolve", "Parameters", None))
        self.label_14.setText(_translate("Gsolve", "Resolution (m)", None))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.Importdata), _translate("Gsolve", "Import DEM Data", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Latitude", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Longitude", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Eastings (m)", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(4)
        item.setText(_translate("Gsolve", "Northings (m)", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(5)
        item.setText(_translate("Gsolve", "Height (m)", None))
        item = self.EastingsNorthingsTC.horizontalHeaderItem(6)
        item.setText(_translate("Gsolve", "DEM Height (m)", None))
        self.ImportdatapointsTC.setText(_translate("Gsolve", "Import Data Points", None))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_6), _translate("Gsolve", "Import Observation Points", None))
        self.groupBox.setTitle(_translate("Gsolve", "Parameters", None))
        self.label_12.setText(_translate("Gsolve", "Outter Radius (m) ", None))
        self.outterradTC.setText(_translate("Gsolve", "120000", None))
        self.innerradTC.setText(_translate("Gsolve", "170", None))
        self.label_11.setText(_translate("Gsolve", "Inner Radius (m) ", None))
        self.label_13.setText(_translate("Gsolve", "Density (g/cm^3)", None))
        self.density.setText(_translate("Gsolve", "2.67", None))
        self.CalcTC.setText(_translate("Gsolve", "Calculate Terrain Corrections", None))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_7), _translate("Gsolve", "Calculate Terrain Correction", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Latitude", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Longitude", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Eastings (m)", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(4)
        item.setText(_translate("Gsolve", "Northings (m)", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(5)
        item.setText(_translate("Gsolve", "Height (m)", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(6)
        item.setText(_translate("Gsolve", "DEM Height (m)", None))
        item = self.EastingsNorthingsTC_results.horizontalHeaderItem(7)
        item.setText(_translate("Gsolve", "Terrain Corr (mGal)", None))
        self.ExportTCresults.setText(_translate("Gsolve", "Export", None))
        item = self.TCparameter_results.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.TCparameter_results.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Density (kg/m^3)", None))
        item = self.TCparameter_results.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Resolution (m)", None))
        item = self.TCparameter_results.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Inner Radius (m)", None))
        item = self.TCparameter_results.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Outter Radius (m)", None))
        self.tabWidget_7.setTabText(self.tabWidget_7.indexOf(self.tab_8), _translate("Gsolve", "Results", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Gsolve", "Terrain Corrections", None))
        self.menu_File.setTitle(_translate("Gsolve", "&File", None))
        self.menuHelp.setTitle(_translate("Gsolve", "Help", None))
        self.dockWidget.setWindowTitle(_translate("Gsolve", "General", None))
        self.CalibrationTabView.setSortingEnabled(True)
        item = self.CalibrationTabView.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.CalibrationTabView.verticalHeaderItem(1)
        item.setText(_translate("Gsolve", "2", None))
        item = self.CalibrationTabView.verticalHeaderItem(2)
        item.setText(_translate("Gsolve", "3", None))
        item = self.CalibrationTabView.verticalHeaderItem(3)
        item.setText(_translate("Gsolve", "4", None))
        item = self.CalibrationTabView.verticalHeaderItem(4)
        item.setText(_translate("Gsolve", "5", None))
        item = self.CalibrationTabView.verticalHeaderItem(5)
        item.setText(_translate("Gsolve", "6", None))
        item = self.CalibrationTabView.verticalHeaderItem(6)
        item.setText(_translate("Gsolve", "7", None))
        item = self.CalibrationTabView.verticalHeaderItem(7)
        item.setText(_translate("Gsolve", "8", None))
        item = self.CalibrationTabView.verticalHeaderItem(8)
        item.setText(_translate("Gsolve", "9", None))
        item = self.CalibrationTabView.verticalHeaderItem(9)
        item.setText(_translate("Gsolve", "10", None))
        item = self.CalibrationTabView.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Lower", None))
        item = self.CalibrationTabView.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Upper", None))
        item = self.CalibrationTabView.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Factor", None))
        self.ImportNewCalTab.setText(_translate("Gsolve", "Import New", None))
        self.RemoveCalTab.setText(_translate("Gsolve", "Remove this calibration table", None))
        self.ImportNewAbdG.setTabText(self.ImportNewAbdG.indexOf(self.tab_2), _translate("Gsolve", "Calibration Tables", None))
        self.AbsGTabview.setSortingEnabled(True)
        item = self.AbsGTabview.verticalHeaderItem(0)
        item.setText(_translate("Gsolve", "1", None))
        item = self.AbsGTabview.verticalHeaderItem(1)
        item.setText(_translate("Gsolve", "2", None))
        item = self.AbsGTabview.verticalHeaderItem(2)
        item.setText(_translate("Gsolve", "3", None))
        item = self.AbsGTabview.verticalHeaderItem(3)
        item.setText(_translate("Gsolve", "4", None))
        item = self.AbsGTabview.verticalHeaderItem(4)
        item.setText(_translate("Gsolve", "5", None))
        item = self.AbsGTabview.horizontalHeaderItem(0)
        item.setText(_translate("Gsolve", "Name", None))
        item = self.AbsGTabview.horizontalHeaderItem(1)
        item.setText(_translate("Gsolve", "Absolute Gravity", None))
        item = self.AbsGTabview.horizontalHeaderItem(2)
        item.setText(_translate("Gsolve", "Latitude", None))
        item = self.AbsGTabview.horizontalHeaderItem(3)
        item.setText(_translate("Gsolve", "Longitude", None))
        self.RemoveAbsG.setText(_translate("Gsolve", "Remove Selected", None))
        self.SaveNewAbsG.setText(_translate("Gsolve", "Save", None))
        self.AddNewAbsG.setText(_translate("Gsolve", "Add New", None))
        self.ImportNewAbsG.setText(_translate("Gsolve", "Import New", None))
        self.ImportNewAbdG.setTabText(self.ImportNewAbdG.indexOf(self.widget), _translate("Gsolve", "Absolute Gravity Sites", None))
        self.actionNew.setText(_translate("Gsolve", "New", None))
        self.actionSave.setText(_translate("Gsolve", "Save", None))
        self.actionOpen.setText(_translate("Gsolve", "Open", None))
        self.actionExit.setText(_translate("Gsolve", "Exit", None))
        self.actionGsolve_Help.setText(_translate("Gsolve", "Gsolve Help", None))
        self.actionAbout.setText(_translate("Gsolve", "About", None))

from matplotlibwidget import MatplotlibWidget
